### ISSUE TITLE
empty ResourceDiscoveryRequest().get_service_info(auth.access_token) for OneDrive Business account

### ISSUE THREAD

**Issue by zioalex** [OneDrive/onedrive-sdk-python#119]
Hi guys,
I am not able to get the list of service available for a OneDrive Business account.

I created a new app in https://apps.dev.microsoft.com/ and added a redirect URLs as described in the doc.

I used the script provided by you customized with my own:
redirect_url = http://localhost:5000/login/onedrive-authorized
client_id = 'xxxx-xxxx-xxxx-xxxx-xxxxxx'
client_secret = 'xxxxxxxxxxx'

As output of the script I expect to see my appname but the list is empty.
I tried to run it from ipython3 and I can see the token ( auth.access_token ) and refresh it. Therefore I think that the authorization process is working.

But the service_info list is empty:
```
In [52]: service_info = ResourceDiscoveryRequest().get_service_info(auth.access_token)
In [53]: service_info
Out[53]: []
```

**Comment by ivanskj** [comment]
Exactly the same issue here

**Comment by zioalex** [comment]
Hi guys, no update here?

**Comment by ruhveen** [comment]
I'm also experiencing the same behaviour,
any update?

**Comment by jwatsn** [comment]
Same issue

**Comment by segalion** [comment]
Me too.
The reason is here:
https://dev.office.com/blogs/outlook-rest-api-v1-0-office-365-discovery-and-live-connect-api-deprecation

Today, we are announcing the **deprecation of the Office 365 discovery service** in favor of using the Microsoft Graph. Deprecation begins on January 10th, 2018. **Newly registered apps will not be able to access the Office 365 discovery service.** Existing apps can continue to use the service until November 1st, 2019. From November 1st, 2019 onward, the Office 365 discovery service will be fully decommissioned, and no apps will be able to use the service anymore.

So until this is not fixed with new "graph api", new clients cant use onedrive-sdk-python anymore.

Please we need an upgrade!!!

**Comment by KTibow** [comment]
@zioalex, @ivanskj, @ruhveen, @jwatsn, @segalion, upgrade your library and client_id/client_secret. I'm not using OneDrive for business, but this impacts every kind of OneDrive, and for me it works.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
