### ISSUE TITLE
Authentcation not working in windows server 2012 and 2016

### ISSUE THREAD

**Issue by prakashpandey** [OneDrive/onedrive-sdk-python#135]
I am trying to download files from onedrive using python SDK. My code is working fine on Ubuntu 18.04, Windows 7 and Windows 2008 server. When I am trying to run the same application on windows server 2012, 2016 my application stuck at `code = GetAuthCodeServer.get_auth_code(auth_url, conf.redirect_uri)`.

I can see my python code opens a tab in my chrome, tell me to sign in and then gets closed. 
This same behavior I see when I run in Ubuntu or windows server 2008 but here it works as intended. 
But, in the case of Windows 2012, 2016 it stuck at `code = GetAuthCodeServer.get_auth_code(auth_url, conf.redirect_uri)`

Code:

```
@staticmethod
    def auth():
        """
            static method to authanticate with onedrive
        """
        log.debug("__INIT__ auth")
        scopes = ['wl.signin', 'wl.offline_access', 'onedrive.readwrite']
        OneDrive.client = onedrivesdk.get_default_client(client_id = conf.client_id, scopes = scopes)
        OneDrive.auth_provider = OneDrive.client.auth_provider
        auth_url = OneDrive.auth_provider.get_auth_url(conf.redirect_uri)
        # this will block until we have the code
        code = GetAuthCodeServer.get_auth_code(auth_url, conf.redirect_uri)
        OneDrive.auth_provider.authenticate(code, conf.redirect_uri, conf.client_secret)
        # # Save the session for later
        # OneDrive.auth_provider.save_session()
        log.debug("__DONE__ auth")
```

**Comment by KTibow** [comment]
@prakashpandey do you still have the issue? If it closes, then it received the text but didn't close, because it has to receive it and send code that tells the window to close. Try the other method: 
```python3
import onedrivesdk

redirect_uri = 'http://localhost:8080/'
client_secret = 'your_client_secret'
client_id='your_client_id'
api_base_url='https://api.onedrive.com/v1.0/'
scopes=['wl.signin', 'wl.offline_access', 'onedrive.readwrite']

http_provider = onedrivesdk.HttpProvider()
auth_provider = onedrivesdk.AuthProvider(
    http_provider=http_provider,
    client_id=client_id,
    scopes=scopes)

client = onedrivesdk.OneDriveClient(api_base_url, auth_provider, http_provider)
auth_url = client.auth_provider.get_auth_url(redirect_uri)
# Ask for the code
print('Paste this URL into your browser, approve the app\'s access.')
print('Copy everything in the address bar after "code=", and paste it below.')
print(auth_url)
code = input('Paste code here: ')

client.auth_provider.authenticate(code, redirect_uri, client_secret)
```
Or try [saving the session](https://github.com/KTibow/onedrive-sdk-python#saving-and-loading-a-session) and copying the `session.pickle` file.
Troubleshooting:

- If you quit it with Ctrl-C while it's stuck, what's the stack trace?
- Do you see something like `GET http://localhost:8080/?code=secret_code_that_im_not_sharing`?

I have to ask, why are you running this on a server? Do you need to serve files? I'm not sure, but it would make sense if you're renting your OneDrive it wouldn't be allowed in the terms of service.

If this solved your issue, consider closing.

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
