### ISSUE TITLE
pip install --user onedrivesdk : NotADirectoryError: [Errno 20] Not a directory NOTICE.rst

### ISSUE THREAD

**Issue by QGB** [OneDrive/onedrive-sdk-python#167]
In [63]: pip install --user  onedrivesdk
Collecting onedrivesdk
  Using cached https://files.pythonhosted.org/packages/b3/76/9a3fe5b36079f5c40b33c89ad6f7737e3b8609010a80c9ed24d762ddb93e/onedrivesdk-2.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-kwl8twtt/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-kwl8twtt/onedrivesdk/setup.py/../NOTICE.rst'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-kwl8twtt/onedrivesdk/
Note: you may need to restart the kernel to use updated packages.

**Comment by TheSeriousProgrammer** [comment]
yeah I am also having the same issue? you got a fix?

**Comment by earonesty** [comment]
You can try `pip install onedrivesdk-fork` ... a fork we built to deal with some of the issues we were having.   Also, we merged in some of the bugfixes people have posted.

**Comment by HasibulKabir** [comment]
If you want to install this repo try: `pip install https://github.com/OneDrive/onedrive-sdk-python/archive/master.zip` This may work.

**Comment by rvernica** [comment]
@QGB I would update the title to `pip install NotADirectoryError: [Errno 20] Not a directory NOTICE.rst` I got the exact same error except for the kernel warning. I think that is particular to your environment.

Here is my output:
```
> pip3 install --user onedrivesdk
Collecting onedrivesdk
  Downloading https://files.pythonhosted.org/packages/b3/76/9a3fe5b36079f5c40b33c89ad6f7737e3b8609010a80c9ed24d762ddb93e/onedrivesdk-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z7qf9zc1/onedrivesdk/setup.py", line 9, in <module>
        with open(NOTICE, 'r', encoding='utf-8') as f:
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-z7qf9zc1/onedrivesdk/setup.py/../NOTICE.rst'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-z7qf9zc1/onedrivesdk/
```

**Comment by AlexisLessard** [comment]
Same error than @rvernica here. I tried installing onedrivesdk-fork, but I haven't managed to make it work with onedrived thus far (which is what I'm trying to install). I'd really like to get a fix :/

**Comment by songhanpoo** [comment]
> If you want to install this repo try: `pip install https://github.com/OneDrive/onedrive-sdk-python/archive/master.zip` This may work.

this worked for me ! many thanks !

**Comment by KTibow** [comment]
@QGB Is this fixed enough? There are many installation problems.

**Comment by rolandolindberg** [comment]
> > If you want to install this repo try: `pip install https://github.com/OneDrive/onedrive-sdk-python/archive/master.zip` This may work.
> 
> this worked for me ! many thanks !

This work for me too

**Comment by KTibow** [comment]
@rolandolindberg I think it's better to use `pip3 install git+https://github.com/OneDrive/onedrive-sdk-python.git` instead, Github is made for Git.

**Comment by utkarshdalal** [comment]
I have this issue too. I'm surprised this bug still exists over 6 months after it was first reported.

**Comment by KTibow** [comment]
@utkarshdalal this repo isn't maintained anymore, as you can see. As for proof:
- Latest **commit**: [December 1st, 2016](https://github.com/OneDrive/onedrive-sdk-python/commit/e5642f8cad8eea37a4f653c1a23dfcfc06c37110)
- Latest **merged PR**: [Dec 1, 2016](https://github.com/OneDrive/onedrive-sdk-python/pull/86)

**Top 4 contributors by commits:**

- @cdmayer, 50 commits. **Last activity (whole GitHub): [Nov 10, 2016](https://github.com/OneDrive/onedrive-sdk-dotnet-msa-auth-adapter/commit/388ac5a242ccadd658d24c7b22b913be32be721e)**
- @D4N14L, 31 commits. **Last activity (whole GitHub): [May 13, 2020](https://github.com/pnpm/pnpm/commit/7b485c61e0e1a91066a88604c4125b215bcf97cf)**
- @wiktorn, 10 commits. **Last activity (whole GitHub): [May 30, 2020](https://github.com/wiktorn/Overpass-API/commit/97c1fe7db1e59bf8d0e248004e156e078a9f8d00)**
- @mimisasouvanh, 5 commits. **Last activity (whole GitHub): [May 13, 2020](https://github.com/MicrosoftDocs/PlayReady/commit/fae8ee6eb03dfb7ce912c4f26d29df43bd9359ec)**

**I've made a [PR](https://github.com/OneDrive/onedrive-sdk-python/pull/174)** and @mimisasouvanh [did say she'd poke around to see if anybody could own it](https://github.com/OneDrive/onedrive-sdk-python/pull/174#issuecomment-618721469), but so far she hasn't gotten back.

**As for the future** of `onedrivesdk-python`, I'd recommend everyone move to [onedrivesdk-fork](https://github.com/AtakamaLLC/onedrive-sdk-python). As for the future of this issue, it's under @QGB's control since they opened it, and as far as I'm concerned as long as the bug still happens it's a valid issue.

**Please, help tidy this repository. Don't lose hope.**

**Comment by baywet** [comment]
Thank you for reaching out and for your patience. This SDK is being officially deprecated. See #209 for more information
