### ISSUE TITLE
File size corruption issue on uploaded files

### ISSUE THREAD

**Issue by ncw** [OneDrive/onedrive-sdk-python#27]
[ **NB** I've put the files from this report in [a gist](https://gist.github.com/ncw/1beadd7258ca87a6ca55)  which you may find easier to use.]

To reproduce, run the python program `onedrive_bug.py`.  This needs the python onedrivesdk. This uploades the file `goof.png` repeatedly, to the root of your onedrive as `1.png`, `2.png`, etc.

If you run it after a while you'll see a size mis-match.

This means that the 97k file is apparently 200k.  If you look in the web interface it also appears as 200k, however if you download it is really only 97k.

I don't think this is a bug in the python library, rather a bug in Onedrive.

I think the bug depends on the particular file being uploaded.

A user of my program `rclone` ( @Darkvater ) noticed the file corruptions originally in ncw/rclone#399 and supplied the png file which is used for the demo here.

This means that this bug has been reproduced with the Python SDK and my own Go SDK and from at least 4 different environments (computers, OS, net connections etc).

This log is from running `onedrive_bug.py` on Linux Ubuntu Wily 15.10 with python 2.7.10 and the onedrive sdk master installed in a virtualenv.

```
$ python onedrive_bug.py 
Created new window in existing browser session.
127.0.0.1 - - [25/Mar/2016 16:38:50] "GET /?code=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx HTTP/1.1" 200 -
Uploaded test file: 0.png, size 97258
Uploaded test file: 1.png, size 97258
Uploaded test file: 2.png, size 97258
Uploaded test file: 3.png, size 97258
Uploaded test file: 4.png, size 97258
Uploaded test file: 5.png, size 97258
Uploaded test file: 6.png, size 205029
**** Size mismatch
Uploaded test file: 7.png, size 205029
Uploaded test file: 8.png, size 205029
Uploaded test file: 9.png, size 205029
Uploaded test file: 10.png, size 97258
**** Size mismatch
Uploaded test file: 11.png, size 97258
Uploaded test file: 12.png, size 97258
Uploaded test file: 13.png, size 97258
```

Here is onedrive_bug.py

``` python
#!/usr/bin/env python
"""
This demonstrates a bug in onedrive
"""

import os
import onedrivesdk
from onedrivesdk.helpers import GetAuthCodeServer
import SocketServer
from datetime import datetime

SocketServer.TCPServer.allow_reuse_address = True # monkey patch so as to set SO_REUSEADDR
GetAuthCodeServer.allow_reuse_address = True

TEST_FILE="goof.png"

def main():
    redirect_uri = "http://localhost:8080/"
    client_secret = "BqaTYqI0XI7wDKcnJ5i3MvLwGcVsaMVM"

    client = onedrivesdk.get_default_client(client_id='00000000481695BB',
                                            scopes=['wl.signin',
                                                    'wl.offline_access',
                                                    'onedrive.readwrite'])
    auth_url = client.auth_provider.get_auth_url(redirect_uri)

    # Block thread until we have the code
    code = GetAuthCodeServer.get_auth_code(auth_url, redirect_uri)
    # Finally, authenticate!
    client.auth_provider.authenticate(code, redirect_uri, client_secret)

    root = client.item(drive="me", id="root")
    last_uploaded_size = None
    for i in range(100):
        name = "%d.png" % i
        uploaded_file = root.children[name].upload(TEST_FILE)
        print "Uploaded test file: %s, size %d" % (name, uploaded_file.size)
        if last_uploaded_size != None:
            if last_uploaded_size != uploaded_file.size:
                print "**** Size mismatch"
        last_uploaded_size = uploaded_file.size

if __name__ == "__main__":
    main()
```

And here is `goof.png`
![goof](https://cloud.githubusercontent.com/assets/536803/14049123/0e4c660a-f2ab-11e5-97da-754cf539657c.png)

**Comment by cdmayer** [comment]
Indeed, this is the same bug that you linked to in #399 in the OneDrive repo. This is expected behavior for now. The fact that you're only reproducing the bug sometimes is due to the fact that thumbnails are generated async, so sometimes you're getting back the thumbnail size (yielding a larger file size) and sometimes you're getting back the original size. Either way, this is not a bug in the Python SDK. I would recommend voting for this issue on [UserVoice](https://onedrive.uservoice.com/forums/262982-onedrive/suggestions/6711029-fix-size-metadata-bug) . Thanks for reporting.

**Comment by Darkvater** [comment]
Hi, I'm the original reporter for rclone and have one outstanding question having read through all replies on this matter. As this is caused by a bug in OneDrive due to thumbnail file generation and stream selection it is impossible to verify the upload integrity through the API. Okay, I understand.

But how are uploads verified through the browser upload, the windows or android onedrive client? Are they using a different API, some internal method of verification? Are all uploads simply unverified and just assumed to be correct? I am quite baffled at the offhand handling of this issue by the OneDrive team as it sounds really serious to me.

**Comment by rgregg** [comment]
TCP error recovery takes care of most of the validation that bytes put into the stream on one side of the connection are received on the other end. If you want to validate that the server copy of the file is identical to the file you started with, the only sure way to do that is to hash the local file, and then retrieve the hash the server calculated for the file from the [hashes facet](https://dev.onedrive.com/facets/hashes_facet.htm).

As I'm sure you know, comparing the file size would do nothing to confirm the file is the same content, only that it is the same length. If you want to verify the contents of the file, the hash is the only way.

Using an [upload session](https://dev.onedrive.com/items/upload_large_files.htm) ensures that your client doesn't have to compete with another client potentially modifying the same file. You can also use eTags to ensure consistency between operations on a file so that the expected server state and actual server state match.
