### ISSUE TITLE
ValueError when uploading large file

### ISSUE THREAD

**Issue by gyma11** [OneDrive/onedrive-sdk-python#56]
When I try to upload large files (500MB - 2000MB) I often get the following exception:

> Traceback (most recent call last):
>   File "OneDriveUpload.py", line 56, in UploadFile
>     client.item(drive="me", path=remoteFilePath).upload_async(localFilePath)
>   File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 170, in fragment_upload_async
>     resp = upload_builder.post(i \* **PART_SIZE, length)
>   File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 118, in post
>     return self.request(begin, length, options).post()
>   File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/version_bridge/fragment_upload.py", line 56, in post
>     entity = UploadSession(json.loads(self.send(data=self._file_handle).content))
>   File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/request_base.py", line 151, in send
>     data=data)
>   File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_provider.py", line 71, in send
>     custom_response = HttpResponse(response.status_code, response.headers, response.text)
>   File "/usr/local/lib/python3.4/dist-packages/onedrivesdk/http_response.py", line 46, in __init**
>     message = json.loads(self.content)
>   File "/usr/lib/python3.4/json/**init**.py", line 318, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
>     raise ValueError(errmsg("Expecting value", s, err.value)) from None
> ValueError: Expecting value: line 1 column 1 (char 0)

Anyone else having this issue?

Using python 3.4 and latest sdk (1.1.2)

**Comment by ambreengames** [comment]
I am also having the exact same issue with the same software configuration when trying to upload large files (although < 10GB in size)

This happens randomly a couple of minutes after starting the upload operation using the upload_async function but lately (since around 2 days ago) it has been happening a lot, according to my logs. By looking at the error stack trace, it seems related to the parsing of JSON code.

No changes were made on my side of the code and according to the logs everything was running smoothly until 2 days ago. So I'm tempted to believe that a recent change in the API servers may have triggered this issue.

**Comment by ambreengames** [comment]
This is becoming a bigger problem every day...

If I keep trying to upload the same file over and over again, after a really a lot of tries, it will eventually work. But this procedure cannot be considered a (temporary) solution, as it wastes really a lot of bandwidth (and time!) in the failed upload attempts both on my side and on the side of the OneDrive API servers.

(Just a wild guess: Could this be related to the use of gzip compression in the API server responses?)

**Comment by cdmayer** [comment]
Please give the following fix a shot: https://github.com/OneDrive/onedrive-sdk-python/pull/57

Basically, we already ignore 500-range errors for up to 5 retries per chunk. This will add blank response bodies to that bucket.

**Comment by cdmayer** [comment]
After some thought I have made some changes to #57. I have a feeling that you're getting an occasional 408 (Timeout), but we can't see it because of a bug in `HttpResponse`. I fixed that, and I made `fragment_upload` ignore 408 along with 500-block errors. Please give this a try. If it doesn't work, please be sure to let me know what error code you're getting.

**Comment by cdmayer** [comment]
Uploaded version 1.1.3 to PyPi, which includes #57. You should be able to use `pip` to get the new version! Let me know if you have other issues.
