### ISSUE TITLE
Resume upload

### ISSUE THREAD

**Issue by zinzindane** [OneDrive/onedrive-sdk-python#64]
How resume upload's? (large file)

please an example

**Comment by cdmayer** [comment]
Right now, the `fragment_upload` [code](https://github.com/OneDrive/onedrive-sdk-python/blob/master/src/onedrivesdk/version_bridge/fragment_upload.py#L135) does not reason about the ranges remaining in a given file. That information _is_ returned by the API in the `session` model. You would want to use some of the same logic as is used in `fragment_upload_async`. In fact, you could refactor that method so that sending the requests and handling retries (lines 165-189 approximately) are one single method, which you could use in your own code. Then, here's what your code would do:
1. Create a session using `ItemRequestBuilder.create_session(item).post()`
2. Upload some chunks
3. When you need to pause the upload, take note of the `session`'s URL and save it for later
4. When the app is re-loaded, use the URL you saved to get the `session` information
5. Use the `next_expected_ranges` property to determine what requests remain
6. Return to 2, keep repeating until all chunks are uploaded

This is definitely an advanced feature of the SDK. It would be much easier to just start the upload from the beginning if your app crashes or is forced to quit while uploading a large file (although understandably not always a great solution).
